CREATE SCHEMA IF NOT EXISTS INTEGRACAO;
USE INTEGRACAO;
CREATE TABLE IF NOT EXISTS admin(
    id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(60) NOT NULL,
    senha VARCHAR(60) NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS fotos(
    id INT NOT NULL AUTO_INCREMENT,
    foto LONGBLOB NOT NULL,
    tipo VARCHAR(6) NOT NULL,
    sinopse VARCHAR(150) NOT NULL,
    classificacao INT NOT NULL,
    nomeF VARCHAR(50) NOT NULL,
    genero VARCHAR(15) NOT NULL,
    PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS videos(
    id INT NOT NULL AUTO_INCREMENT,
    video LONGBLOB NOT NULL,
    tipo VARCHAR(6) NOT NULL,
    PRIMARY KEY(id)
);
INSERT INTO admin(nome, senha) VALUES("daniel", "123456");